_target_: src.models.segmentation_module.SegmentationModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-03
  weight_decay: 0.0
head_lr: null

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: 'max'
  factor: 0.2
  patience: 4
  threshold: 0.01
  threshold_mode: 'rel'
metric_monitored: 'val/acc'

warmup_scheduler:
  _target_: src.models.components.utils.WarmupScheduler
  _partial_: true
  min_lr: 1.0e-05
  max_lr: ${model.optimizer.lr}
  fract: 0.05 # Fraction of the total number of iterations to warmup


net:
  img_size: ${data.imagesize}
  num_channels: ${data.num_channels}
  num_classes: ${data.num_classes}

# tiff saving parameters
save_freq: 1000 # Save predictions every n epochs (always include the last epoch)
val_overlap: ${data.val_overlap}
test_overlap: ${data.test_overlap}
# Compile model for faster training with pytorch 2.0
compile: false
num_classes: ${model.net.num_classes}
# use_model_loss: False Not applicable to any model

index_to_ignore: ${data.index_to_ignore} #index to ignore in the loss
