# @package _global_
defaults:
  - _seg_default@model

model:
  net:
    _target_: src.models.components.flatten_swin.Flatten_swin_module
    pretrained: True
    pretrained_path: ${paths.data_dir}/Models/flatten_ckpt_swin_b.pth

    img_size: 224
    patch_size: 4
    window_size: 56
    drop_path_rate: 0.1  # CAREFUL. Is it 0.1 or 0.5??
    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
    segmentation_head:
      _partial_: True
      _target_: src.models.components.utils.SimpleSegmentationHead
      decoder_stride: 32
    num_register_tokens: 0
    la:
      attn_type: "LLSS"  
      focusing_factor: 3
      kernel_size: 5


data:
    imageside: 224
    imagesize: 224
