# @package _global_
defaults:
  - RT_Swin2_S

model:
  net:
    pretrained: True
    pretrained_path: ${paths.data_dir}Models/swinv2_base_patch4_window8_256.pth

    embed_dim: 128
    depths: [2, 2, 18, 2]
    num_heads: [4, 8, 16, 32]
