# @package _global_
defaults:
  - RT_Swin2_S

model:
  net:
    pretrained: True
    pretrained_path: ${paths.data_dir}Models/swinv2_large_patch4_window12_192_22k.pth

    window_size: 12
    embed_dim: 192
    depths: [2, 2, 18, 2]
    num_heads: [6, 12, 24, 48]
